/* Generated from Java with JSweet 2.3.0-SNAPSHOT - http://www.jsweet.org */
class login {
    static main(args) {
        console.log("Creating form");
        let form = document.createElement("form");
        form.action = login.SERVLET_URL;
        form.method = "POST";
        console.log("Form Done");
        console.log("creating mail label");
        let labelMail = document.createElement("label");
        labelMail.className = "form-control-plaintext";
        labelMail.textContent = "Email:";
        console.log("creating pw label");
        let labelPw = document.createElement("label");
        labelPw.className = "form-control-plaintext";
        labelPw.textContent = "Password:";
        console.log("creating email input");
        let email = document.createElement("input");
        email.name = "email";
        email.className = "form-control";
        email.type = "email";
        console.log("creating password input");
        let password = document.createElement("input");
        password.name = "password";
        password.className = "form-control";
        password.type = "password";
        let loginButton = document.createElement("input");
        loginButton.type = "submit";
        loginButton.name = "loginButton_button";
        loginButton.className = "btn btn-primary";
        loginButton.value = "LOGIN";
        console.log("creating signup anchor element");
        let signupButton = document.createElement("a");
        signupButton.className = "btn btn-primary";
        signupButton.href = login.SIGNUP_URL;
        console.log("creating signupButton label");
        let labelSignUp = document.createElement("label");
        labelSignUp.textContent = "SIGN UP";
        let divMail = document.createElement("div");
        divMail.className = "form-group";
        $(labelMail).css("marginLeft", "5px");
        $(labelMail).css("fontWeight", "600");
        $(labelMail).css("fontSize", "x-large");
        $(labelMail).css("color", "rgba(64, 38, 94, 1)");
        $(email).css("width", "320px");
        $(email).css("height", "45px");
        $(email).css("marginLeft", "25px");
        $(email).css("fontWeight", "500");
        $(divMail).append(labelMail);
        $(divMail).append(email);
        let divPw = document.createElement("div");
        divPw.className = "form-group";
        $(labelPw).css("marginLeft", "5px");
        $(labelPw).css("fontWeight", "600");
        $(labelPw).css("fontSize", "x-large");
        $(labelPw).css("color", "rgba(64, 38, 94, 1)");
        $(password).css("width", "320px");
        $(password).css("height", "45px");
        $(password).css("marginLeft", "25px");
        $(password).css("fontWeight", "500");
        $(divPw).append(labelPw);
        $(divPw).append(password);
        let divButton = document.createElement("div");
        divButton.className = "form-group submit-button";
        $(divButton).append(loginButton);
        let divLink = document.createElement("div");
        divLink.className = "form-group";
        $(signupButton).css("backgroundColor", "rgb(255, 255, 255)");
        $(signupButton).css("sizes", "100px");
        $(signupButton).css("height", "30px");
        $(signupButton).css("width", "100px");
        $(signupButton).css("marginLeft", "135px");
        $(labelSignUp).css("marginTop", "-4px");
        $(labelSignUp).css("marginRight", "5px");
        $(labelSignUp).css("color", "rgba(64, 38, 94, 1)");
        $(signupButton).append(labelSignUp);
        $(divLink).append(signupButton);
        $(form).css("margin", "110px 500px 50px");
        console.log("adding to form");
        $(form).append(divMail);
        $(form).append(divPw);
        $(form).append(divButton);
        $(form).append(divLink);
        console.log("adding to body");
        $("body").append(form);
    }
}
login.SERVLET_URL = "login.jsp";
login.SIGNUP_URL = "signup.html";
login["__class"] = "login";
login.main(null);
