/* Generated from Java with JSweet 2.3.0-SNAPSHOT - http://www.jsweet.org */
class signup {
    static main(args) {
        console.log("Creating form");
        let form = document.createElement("form");
        form.action = signup.SERVLET_URL;
        form.method = "POST";
        console.log("Form Done");
        $(form).css("margin", "100px 350px 200px");
        console.log("creating form title");
        let title = document.createElement("label");
        title.className = "form-plaintext";
        title.textContent = "REGISTRAZIONE";
        $(title).css("fontWeight", "500");
        $(title).css("fontSize", "x-large");
        $(title).css("color", "black");
        console.log("creating email input");
        let email = document.createElement("input");
        email.name = "email";
        email.required = true;
        email.className = "form-control";
        email.type = "email";
        email.placeholder = "Email*";
        console.log("creating password input");
        let password = document.createElement("input");
        password.name = "password";
        password.className = "form-control";
        password.type = "password";
        password.placeholder = "Password*";
        password.required = true;
        let password2 = document.createElement("input");
        password2.name = "password2";
        password2.className = "form-control";
        password2.type = "password";
        password2.placeholder = "Ripeti password*";
        password2.required = true;
        let labelLangNat = document.createElement("label");
        labelLangNat.className = "form-control-plaintext";
        labelLangNat.textContent = "Selezionare le proprie lingue native: *";
        $(labelLangNat).css("fontWeight", "500");
        let cbItalianNat = document.createElement("input");
        cbItalianNat.name = "cbNat";
        cbItalianNat.value = "Italiano";
        cbItalianNat.className = "form-control";
        cbItalianNat.type = "checkbox";
        $(cbItalianNat).css("height", "20");
        $(cbItalianNat).css("width", "20");
        $(cbItalianNat).css("position", "absolute");
        $(cbItalianNat).css("marginLeft", "15");
        $(cbItalianNat).css("marginTop", "15");
        let labelITNat = document.createElement("label");
        labelITNat.className = "form-control-plaintext";
        labelITNat.textContent = "ITALIANO";
        $(labelITNat).css("display", "inline-block");
        $(labelITNat).css("vertical-align", "top");
        $(labelITNat).css("marginLeft", "55px");
        $(labelITNat).css("marginTop", "5px");
        let cbEnglishNat = document.createElement("input");
        cbEnglishNat.name = "cbNat";
        cbEnglishNat.value = "English";
        cbEnglishNat.className = "form-control";
        cbEnglishNat.type = "checkbox";
        $(cbEnglishNat).css("height", "20");
        $(cbEnglishNat).css("width", "20");
        $(cbEnglishNat).css("position", "absolute");
        $(cbEnglishNat).css("marginLeft", "15");
        $(cbEnglishNat).css("marginTop", "15");
        let labelENNat = document.createElement("label");
        labelENNat.className = "form-control-plaintext";
        labelENNat.textContent = "ENGLISH";
        $(labelENNat).css("display", "inline-block");
        $(labelENNat).css("vertical-align", "top");
        $(labelENNat).css("marginLeft", "55px");
        $(labelENNat).css("marginTop", "5px");
        let labelLangOther = document.createElement("label");
        labelLangOther.className = "form-control-plaintext";
        labelLangOther.textContent = "Selezionare altre lingue conosciute:   (Opzionale)";
        $(labelLangOther).css("fontWeight", "500");
        let labelLiv = document.createElement("label");
        labelLiv.className = "form-control-plaintext";
        labelLiv.textContent = "Indicare anche il relativo livello CEFR di competenza.";
        $(labelLiv).css("fontSize", "small");
        $(labelLiv).css("fontWeight", "450");
        $(labelLiv).css("color", "rgba(71, 66, 77, 1)");
        $(labelLiv).css("marginLeft", "15");
        let cbItalianOther = document.createElement("input");
        cbItalianOther.name = "cbItalianOther";
        cbItalianOther.value = "Italiano";
        cbItalianOther.className = "form-control";
        cbItalianOther.type = "checkbox";
        $(cbItalianOther).css("height", "20");
        $(cbItalianOther).css("width", "20");
        $(cbItalianOther).css("position", "absolute");
        $(cbItalianOther).css("marginLeft", "15");
        $(cbItalianOther).css("marginTop", "15");
        let labelITOther = document.createElement("label");
        labelITOther.className = "form-control-plaintext";
        labelITOther.textContent = "ITALIANO";
        $(labelITOther).css("display", "inline-block");
        $(labelITOther).css("vertical-align", "top");
        $(labelITOther).css("marginLeft", "55px");
        $(labelITOther).css("marginTop", "5px");
        $(labelITOther).css("width", "100px");
        let cbEnglishOther = document.createElement("input");
        cbEnglishOther.name = "cbEnglishOther";
        cbEnglishOther.value = "English";
        cbEnglishOther.className = "form-control";
        cbEnglishOther.type = "checkbox";
        $(cbEnglishOther).css("height", "20");
        $(cbEnglishOther).css("width", "20");
        $(cbEnglishOther).css("position", "absolute");
        $(cbEnglishOther).css("marginLeft", "15");
        $(cbEnglishOther).css("marginTop", "15");
        let labelENOther = document.createElement("label");
        labelENOther.className = "form-control-plaintext";
        labelENOther.textContent = "ENGLISH";
        $(labelENOther).css("display", "inline-block");
        $(labelENOther).css("vertical-align", "top");
        $(labelENOther).css("marginLeft", "55px");
        $(labelENOther).css("marginTop", "5px");
        $(labelENOther).css("width", "100px");
        let livIT = document.createElement("select");
        livIT.className = "form-control";
        livIT.name = "livIT";
        let a1 = document.createElement("option");
        a1.text = "A1";
        a1.value = "A1";
        let a2 = document.createElement("option");
        a2.text = "A2";
        a2.value = "A2";
        let b1 = document.createElement("option");
        b1.text = "B1";
        b1.value = "B1";
        let b2 = document.createElement("option");
        b2.text = "B2";
        b2.value = "B2";
        let c1 = document.createElement("option");
        c1.text = "C1";
        c1.value = "C1";
        let c2 = document.createElement("option");
        c2.text = "C2";
        c2.value = "C2";
        let ph = document.createElement("option");
        ph.text = "Livello";
        ph.disabled = true;
        ph.selected = true;
        ph.hidden = true;
        livIT.add(ph);
        livIT.add(a1);
        livIT.add(a2);
        livIT.add(b1);
        livIT.add(b2);
        livIT.add(c1);
        livIT.add(c2);
        $(livIT).css("padding-bottom", "0");
        $(livIT).css("width", "100");
        $(livIT).css("height", "30");
        $(livIT).css("display", "inline-block");
        $(livIT).css("vertical-align", "top");
        $(livIT).css("marginTop", "7");
        $(livIT).css("marginLeft", "10");
        let livEN = document.createElement("select");
        livEN.className = "form-control";
        livEN.name = "livEN";
        let a12 = document.createElement("option");
        a12.text = "A1";
        a12.value = "A1";
        let a22 = document.createElement("option");
        a22.text = "A2";
        a22.value = "A2";
        let b12 = document.createElement("option");
        b12.text = "B1";
        b12.value = "B1";
        let b22 = document.createElement("option");
        b22.text = "B2";
        b22.value = "B2";
        let c12 = document.createElement("option");
        c12.text = "C1";
        c12.value = "C1";
        let c22 = document.createElement("option");
        c22.text = "C2";
        c22.value = "C2";
        let ph2 = document.createElement("option");
        ph2.text = "Livello";
        ph2.value = "";
        ph2.disabled = true;
        ph2.selected = true;
        ph2.hidden = true;
        livEN.add(ph2);
        livEN.add(a12);
        livEN.add(a22);
        livEN.add(b12);
        livEN.add(b22);
        livEN.add(c12);
        livEN.add(c22);
        $(livEN).css("padding-bottom", "0");
        $(livEN).css("width", "100");
        $(livEN).css("height", "30");
        $(livEN).css("display", "inline-block");
        $(livEN).css("vertical-align", "top");
        $(livEN).css("marginTop", "7");
        $(livEN).css("marginLeft", "10");
        console.log("creating signup submit element");
        let signupButton = document.createElement("input");
        signupButton.className = "btn btn-primary";
        signupButton.type = "submit";
        signupButton.name = "signupButton_button";
        signupButton.value = "SIGN UP";
        console.log("creating login anchor element");
        signupButton.onclick = ((livEN, cbEnglishOther, livIT, cbItalianOther, cbItalianNat, cbEnglishNat) => {
            return (x) => {
                cbItalianNat.required = false;
                cbEnglishNat.required = false;
                livIT.required = false;
                livEN.required = false;
                if (!cbItalianNat.checked && !cbEnglishNat.checked) {
                    cbItalianNat.required = true;
                    cbEnglishNat.required = true;
                }
                if (cbItalianOther.checked) {
                    livIT.required = true;
                }
                if (cbEnglishOther.checked) {
                    livEN.required = true;
                }
                return null;
            };
        })(livEN, cbEnglishOther, livIT, cbItalianOther, cbItalianNat, cbEnglishNat);
        let loginButton = document.createElement("a");
        loginButton.className = "btn btn-primary";
        loginButton.href = signup.LOGIN_URL;
        console.log("creating loginButton label");
        let labelLogin = document.createElement("label");
        labelLogin.textContent = "LOGIN";
        let divMail = document.createElement("div");
        divMail.className = "form-group";
        $(divMail).append(email);
        let divPw = document.createElement("div");
        divPw.className = "form-group";
        $(divPw).append(password);
        let divPw2 = document.createElement("div");
        divPw2.className = "form-group";
        $(divPw2).append(password2);
        let divFields = document.createElement("div");
        divFields.className = "form-group";
        $(divFields).append(divMail);
        $(divFields).append(divPw);
        $(divFields).append(divPw2);
        $(divFields).css("marginTop", "30px");
        let divLangNat = document.createElement("div");
        divLangNat.className = "form-group";
        $(divLangNat).append(labelLangNat);
        $(divLangNat).append(cbItalianNat);
        $(divLangNat).append(labelITNat);
        $(divLangNat).append(cbEnglishNat);
        $(divLangNat).append(labelENNat);
        $(divLangNat).css("marginTop", "50px");
        let divLangOtherIT = document.createElement("div");
        divLangOtherIT.className = "form-group";
        $(divLangOtherIT).append(cbItalianOther);
        $(divLangOtherIT).append(labelITOther);
        $(divLangOtherIT).append(livIT);
        let divLangOtherEN = document.createElement("div");
        divLangOtherEN.className = "form-group";
        $(divLangOtherEN).css("marginTop", "-15");
        $(divLangOtherEN).append(cbEnglishOther);
        $(divLangOtherEN).append(labelENOther);
        $(divLangOtherEN).append(livEN);
        let divLangOther = document.createElement("div");
        divLangOther.className = "form-group";
        $(divLangOther).append(labelLangOther);
        $(divLangOther).append(labelLiv);
        $(divLangOther).append(divLangOtherIT);
        $(divLangOther).append(divLangOtherEN);
        $(divLangOther).css("marginTop", "50px");
        let divButton = document.createElement("div");
        divButton.className = "form-group";
        $(signupButton).css("height", "30px");
        $(signupButton).css("width", "100px");
        $(signupButton).css("marginLeft", "500px");
        $(signupButton).css("marginTop", "25px");
        $(signupButton).css("backgroundColor", "rgba(64, 38, 94, 1)");
        $(signupButton).css("color", "white");
        $(signupButton).css("marginTop", "100");
        $(divButton).append(signupButton);
        let divLink = document.createElement("div");
        divLink.className = "form-group";
        $(loginButton).css("backgroundColor", "rgb(255, 255, 255)");
        $(loginButton).css("sizes", "100px");
        $(loginButton).css("height", "30px");
        $(loginButton).css("width", "100px");
        $(loginButton).css("marginLeft", "500px");
        $(labelLogin).css("marginTop", "-4px");
        $(labelLogin).css("marginRight", "5px");
        $(labelLogin).css("color", "rgba(64, 38, 94, 1)");
        $(loginButton).append(labelLogin);
        $(divLink).append(loginButton);
        $(form).append(title);
        $(form).append(divFields);
        $(form).append(divLangNat);
        $(form).append(divLangOther);
        $(form).append(divButton);
        $(form).append(divLink);
        $("body").append(form);
    }
}
signup.SERVLET_URL = "signup.jsp";
signup.LOGIN_URL = "login.html";
signup["__class"] = "signup";
signup.main(null);
